language: cpp
sudo: false
dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install clang-tools
  - sudo apt-get install graphviz
  - sudo apt-get install cmake
  - sudo apt-get install libfl-dev
  - sudo apt-get install flex
  - wget http://ftp.gnu.org/gnu/bison/bison-3.4.2.tar.gz
  - tar -zxvf bison-3.4.2.tar.gz
  - cd bison-3.4.2/
  - sudo ./configure
  - sudo make
  - sudo make install
  - cd ..

script:
  - mkdir build
  - cd build
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake -DCOVERAGE=1 ..
  - scan-build cmake --build .
  - cd tests
  - cp ../../run_tests.sh run_tests.sh
  - sh run_tests.sh

after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"